# Generated by Django 2.1.5 on 2022-03-06 13:45

import Educ8.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseName', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('title', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
                ('Course', models.CharField(max_length=256, verbose_name=Educ8.models.Student)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.OneToOneField(default='DEFAULT', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firstname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lastname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Educ8.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Educ8.Teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='Educ8.Student'),
        ),
    ]
